version: '3'

services:
  app:
    build: .
    volumes:
      - ./project/db:/endomondo_app/project/db
      - ./project/logs:/endomondo_app/project/logs
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
  cron:
    build: .
    command: ["/cron_entrypoint.sh"]
    volumes:
        - ./project/db:/endomondo_app/project/db
        - ./project/logs:/endomondo_app/project/logs
    restart: always
    env_file:
        - .env
